### ISSUE TITLE
Tile blending error

### ISSUE THREAD

**Issue by hugsm** [jpanther/Dectorio#256]
Tiles have errors on corners and painted hazard tiles have error on transition to other tiles, problem is the same regardless if "use default factorio hazard concrete style" is turned on or off

![blending](https://github.com/user-attachments/assets/545cf74e-d556-4824-9709-8c089b1b324e)

Mod list
All other mods disabled except the space age ones and editor extensions

**Comment by Maxoxpower** [comment]
i confirm. those tiles wont work :(

**Comment by MachMainframe** [comment]
Yeah, it's interesting. My save from before Space Age looked fine upon loading. But if I touch anything anywhere near the Dectorio concrete varieties, it does that edge effect in the above photo.

**Comment by Lmello1** [comment]
Confirming again, error still exists for striped concrete variants.

**Comment by jahands** [comment]
Same here :(

**Comment by Maxoxpower** [comment]
hope it will get updated...i love this mod!

**Comment by scotscoder** [comment]
Yep, I can confirm this also happens for me.  The edge effect isn't working.

**Comment by ZettXXII** [comment]
Same here, hope it gets fixed, because I love the additional options.
I found another related bug: the colored concrete can appear transparent in some cases, making the ground below visible.

**Comment by scotscoder** [comment]
> Same here, hope it gets fixed, because I love the additional options. I found another related bug: the colored concrete can appear transparent in some cases, making the ground below visible.

Shove that other bug in another issue.

**Comment by ZettXXII** [comment]
> Shove that other bug in another issue.

Maybe this got fixed with Factorio updates (2.0.22 now), because I saw your reply and I cannot recreate the bug for a screenshot anymore. If it comes up again, I'll report in a new issue.

**Comment by scotscoder** [comment]
> > Shove that other bug in another issue.
> 
> Maybe this got fixed with Factorio updates (2.0.22 now), because I saw your reply and I cannot recreate the bug for a screenshot anymore. If it comes up again, I'll report in a new issue.

It's still happening for me except with anything other than Dectorio tiles.   If I combine Dectorio concrete with, say, stone bricks, I still get the broken border.  That doesn't happen with stock concrete/refined concrete/hazard concrete.

**Comment by Hoochie63** [comment]
I have concrete or reinforced concrete tiles that look like this. Is there any way to fix this?

![image](https://github.com/user-attachments/assets/107214f5-7acd-4c01-a4d4-43d9415c02fc)

**Comment by 0n0w1c** [comment]
It may not be for everyone, but the [Foundations](https://mods.factorio.com/mod/Foundations) mod has implemented a fix.

**Comment by Rosethorns** [comment]
> It may not be for everyone, but the [Foundations](https://mods.factorio.com/mod/Foundations) mod has implemented a fix.

Foundations does so much else to the nature of tile placement, and is not compatible with multiplayers, even "might not be for everyone" does not cover this as a "fix"

**Comment by 0n0w1c** [comment]
Foundations mod no longer offers support for Dectorio.

**Comment by Hoochie63** [comment]
Why did you remove support? Does it cause any errors? :(

**Comment by 0n0w1c** [comment]
The attempt to "fix" the Dectorio hazard concretes results in the hazard concretes layering above the base concretes, when they should merge. I have yet to find a good solution.

**Comment by 0n0w1c** [comment]
@Hoochie63
Foundations mod once again supports Dectorio, but *highly* recommended to enable Dectorio's startup setting 'Use default Factorio Hazard concrete style'.

**Comment by Hoochie63** [comment]
Great news!
Thank you!
